import Season from '../components/Question/Price';

const mockRecommendations = [
  {
    id: 1,
    name: 'Bloom Essence',
    brand: 'Maison Lumière',
    gender: 'Unisex',
    price_tier: 'Mid-Range',
    season: 'Spring',
    activity: 'Casual',
    longevity: 'Mid',
    projection: 'Moderate',
    description:
      'A delicate blend of jasmine and bergamot, perfect for daily elegance. Recommended for spring.',
    main_accord: 'Floral Citrus',
    all_notes: ['Pandan', 'Coconut', 'Jasmine', 'Bergamot'],
    notes_structured: {
      top: ['Bergamot', 'Lemon'],
      middle: ['Jasmine', 'Pandan'],
      base: ['Coconut', 'Musk'],
    },
  },
  {
    id: 2,
    name: 'Midnight Ember',
    brand: 'Obsidian Scents',
    gender: 'Male',
    price_tier: 'Luxury',
    season: 'Winter',
    activity: 'Date Night',
    longevity: 'Eternal',
    projection: 'Strong',
    description:
      'A dark, smoky fragrance designed for cold nights. Features rich leather and warm spices.',
    main_accord: 'Woody Spicy',
    all_notes: ['Oud', 'Leather', 'Black Pepper', 'Smoke'],
    notes_structured: {
      top: ['Black Pepper', 'Cardamom'],
      middle: ['Leather', 'Oud Wood'],
      base: ['Amber', 'Smoke', 'Vanilla'],
    },
  },
  {
    id: 3,
    name: 'Oceanic Drift',
    brand: 'Azure Labs',
    gender: 'Male',
    price_tier: 'Budget',
    season: 'Summer',
    activity: 'Sport',
    longevity: 'Mid',
    projection: 'Moderate',
    description:
      'Fresh and energizing, capturing the essence of the sea breeze. Great for the gym or beach.',
    main_accord: 'Aquatic Fresh',
    all_notes: ['Sea Salt', 'Lime', 'Driftwood'],
    notes_structured: {
      top: ['Lime', 'Sea Salt', 'Mint'],
      middle: ['Sage', 'Lavender'],
      base: ['Driftwood', 'White Musk'],
    },
  },
  {
    id: 4,
    name: 'Velvet Rose',
    brand: 'Royal Botanic',
    gender: 'Female',
    price_tier: 'Mid-Range',
    season: 'Fall',
    activity: 'Formal',
    longevity: 'Long-lasting',
    projection: 'Moderate',
    description:
      'A sophisticated bouquet of roses with a gourmand twist. Elegant and timeless.',
    main_accord: 'Floral Gourmand',
    all_notes: ['Rose', 'Praline', 'Patchouli'],
    notes_structured: {
      top: ['Raspberry', 'Lychee'],
      middle: ['Damask Rose', 'Peony'],
      base: ['Praline', 'Patchouli', 'Vanilla'],
    },
  },
  {
    id: 5,
    name: 'Urban Concrete',
    brand: 'Modernist',
    gender: 'Unisex',
    price_tier: 'Niche',
    season: 'All Season',
    activity: 'Office',
    longevity: 'Mid',
    projection: 'Intimate',
    description:
      'Minimalist and clean. A molecular scent that enhances your natural skin chemistry.',
    main_accord: 'Musky Woody',
    all_notes: ['Iso E Super', 'Ambroxan', 'Cedar'],
    notes_structured: {
      top: ['Pink Pepper'],
      middle: ['Iso E Super', 'Iris'],
      base: ['Ambroxan', 'Cedarwood'],
    },
  },
  {
    id: 6,
    name: 'Golden Hour',
    brand: 'Solstice',
    gender: 'Female',
    price_tier: 'Luxury',
    season: 'Summer',
    activity: 'Casual',
    longevity: 'Long-lasting',
    projection: 'Strong',
    description:
      'Radiant and creamy, smelling like expensive sunscreen and tropical vacations.',
    main_accord: 'Solar Floral',
    all_notes: ['Ylang-Ylang', 'Tuberose', 'Coconut Milk'],
    notes_structured: {
      top: ['Mandarin', 'Solar Notes'],
      middle: ['Ylang-Ylang', 'Tuberose'],
      base: ['Coconut Milk', 'Benzoin'],
    },
  },
  {
    id: 7,
    name: 'Forest Rain',
    brand: 'Nature & Co',
    gender: 'Male',
    price_tier: 'Mid-Range',
    season: 'Spring',
    activity: 'Office',
    longevity: 'Mid',
    projection: 'Moderate',
    description:
      'The smell of damp earth and green pine needles after a heavy rain.',
    main_accord: 'Green Earthy',
    all_notes: ['Pine', 'Vetiver', 'Oakmoss'],
    notes_structured: {
      top: ['Grapefruit', 'Basil'],
      middle: ['Pine Needle', 'Geranium'],
      base: ['Vetiver', 'Oakmoss', 'Cedar'],
    },
  },
  {
    id: 8,
    name: 'Spiced Tobacco',
    brand: "Gentleman's Club",
    gender: 'Male',
    price_tier: 'Luxury',
    season: 'Winter',
    activity: 'Formal',
    longevity: 'Eternal',
    projection: 'Beast',
    description:
      'A powerful, boozy tobacco scent for the confident individual. Very sweet and spicy.',
    main_accord: 'Oriental Spicy',
    all_notes: ['Tobacco Leaf', 'Honey', 'Cinnamon'],
    notes_structured: {
      top: ['Cinnamon', 'Rum'],
      middle: ['Tobacco Leaf', 'Honey'],
      base: ['Tonka Bean', 'Vanilla'],
    },
  },
  {
    id: 9,
    name: 'Citrus Vetiver',
    brand: 'Clean Slate',
    gender: 'Unisex',
    price_tier: 'Budget',
    season: 'Summer',
    activity: 'Casual',
    longevity: 'Weak',
    projection: 'Moderate',
    description:
      'A sharp, clean citrus blast that settles into a dry grassy vetiver. Very refreshing.',
    main_accord: 'Citrus Aromatic',
    all_notes: ['Lemon', 'Vetiver', 'Ginger'],
    notes_structured: {
      top: ['Lemon', 'Bergamot'],
      middle: ['Ginger', 'Neroli'],
      base: ['Vetiver', 'Musk'],
    },
  },
  {
    id: 10,
    name: 'Cashmere Hug',
    brand: 'Soft Touch',
    gender: 'Female',
    price_tier: 'Mid-Range',
    season: 'Fall',
    activity: 'Casual',
    longevity: 'Long-lasting',
    projection: 'Intimate',
    description:
      'Cozy and warm, like wearing a soft cashmere sweater by the fire.',
    main_accord: 'Powdery Musk',
    all_notes: ['White Musk', 'Sandalwood', 'Heliotrope'],
    notes_structured: {
      top: ['Cotton Flower', 'Rice'],
      middle: ['Heliotrope', 'Orange Blossom'],
      base: ['White Musk', 'Sandalwood', 'Vanilla'],
    },
  },
];

export default mockRecommendations;
